.. BMDFM.man
..
.TH BMDFM 1 "13-Aug-2021"

.SH NAME
 fastlisp \-
  FastLisp Compiler with Runtime Environment.

 BMDFMsrv \-
  The "Broken Mind" Data-Flow Machine SMP MIMD Server Unit.

 BMDFMldr \-
  The External Task PROC Unit (The Loader and Listener Pair)
  for the "Broken Mind" Data-Flow Machine.

 BMDFMtrc \-
  The Interactive Tracer Unit
  for the "Broken Mind" Data-Flow Machine.

.SH SYNOPSIS
  Usage0: fastlisp -h|--help
  Usage1: fastlisp -V|--versions
  Usage2: fastlisp [-q|--quiet] <FastLisp_file_name> [args...]
  Usage3: fastlisp [-sd|--showDebugInfo] <FastLisp_file_name> [args...]
  Usage4: fastlisp [-c|--compile2disk] <FastLisp_file_name> [args...]
  Usage5: fastlisp [-cm|--compileMinimized2disk] <FastLisp_file_name>
                   [args...]
  Usage6: fastlisp [-q|--quiet] <Precompiled_FastLisp_file_name>
  Usage7: fastlisp [-sd|--showDebugInfo]
                   <Precompiled_FastLisp_file_name>

Runtime environment variable dump:
  FAST_LISP_CODE_PRINT__TERM_WIDE=0;
  FAST_LISP_CODE_PRINT__CFG_UDF=1;
  FAST_LISP_CODE_PRINT__MODIFIED_SRC=1;
  FAST_LISP_CODE_PRINT__DUMPED_SRC=1;
  FAST_LISP_CODE_PRINT__COMPILED=1;
  FAST_LISP_CODE_PRINT__LINKED=1;
  FAST_LISP_CODE_PRINT__DECOMPILED=1;
  FAST_LISP_MAPCAR_WITH_DECOMPILER=1;
  FAST_LISP_COMPILE_WITH_DEBUGINFO=1;

The following environment variable:
  FAST_LISP_CFGPROFILE_path="fastlisp.cfg"
specifies a configuration profile that can be used for the Global
FastLisp function definitions.
The format of the configuration profile is:
  <(DEFUN ...)>{ <(DEFUN ...)>}  # <EOF>.

  Usage0: BMDFMsrv
  Usage1: BMDFMsrv -h|--help
  Usage2: BMDFMsrv -V|--versions
  Usage3: BMDFMsrv [-d|--daemonize]
  Usage4: BMDFMsrv [-d|--daemonize] -n|--no-logs
  Usage5: BMDFMsrv [-d|--daemonize] -l|--logfile <log_file_name>

Runtime environment variable dump:
  BM_DFM_MAPCAR_WITH_DECOMPILER=1;
  BM_DFM_COMPILE_WITH_DEBUGINFO=1;
  BM_DFM_CFGPROFILE_path="./BMDFMsrv.cfg";
  BM_DFM_PROCstat_path="./PROCstat";
  BM_DFM_CPUPROC_path="./CPUPROC";
  BM_DFM_OQPROC_path="./OQPROC";
  BM_DFM_IORBPROC_path="./IORBPROC";
  BM_DFM_CONNECTION_FILE_path="/tmp/.BMDFMsrv";
  BM_DFM_CONNECTION_NPIP_path="/tmp/.BMDFMsrv_npipe";
  BM_DFM_EMERGENCY_IPC_FILE_path="./freeIPC.inf";
  BM_DFM_LOGFILE_KEEP_NxSIZE="10x10000000";
  BM_DFM_PROCLOGFILE_KEEP_NxSIZE="10x10000000";
  BM_DFM_PROCLOGFILE_path="./PROCs.log";

  Usage0: BMDFMldr -h|--help
  Usage1: BMDFMldr -V|--versions
  Usage2: BMDFMldr [-q|--quiet] <FastLisp_file_name> [args...]
  Usage3: BMDFMldr [-sd|--showDebugInfo] <FastLisp_file_name> [args...]
  Usage4: BMDFMldr [-c|--compile2disk] <FastLisp_file_name> [args...]
  Usage5: BMDFMldr [-q|--quiet] <Precompiled_FastLisp_file_name>
  Usage6: BMDFMldr [-sd|--showDebugInfo]
                   <Precompiled_FastLisp_file_name>

Runtime environment variable dump:
  BM_DFM_CODE_PRINT__TERM_WIDE=0;
  BM_DFM_CODE_PRINT__CFG_UDF=1;
  BM_DFM_CODE_PRINT__MODIFIED_SRC=1;
  BM_DFM_CODE_PRINT__DUMPED_SRC=1;
  BM_DFM_CODE_PRINT__LINKED=1;
  BM_DFM_CODE_PRINT__DFM_UNICODE=1;
  BM_DFM_MAPCAR_WITH_DECOMPILER=1;
  BM_DFM_COMPILE_WITH_DEBUGINFO=1;
  BM_DFM_CONNECTION_FILE_path="/tmp/.BMDFMsrv";
  BM_DFM_CONNECTION_NPIP_path="/tmp/.BMDFMsrv_npipe";

  Usage0: BMDFMtrc
  Usage1: BMDFMtrc -h|--help
  Usage2: BMDFMtrc -V|--versions
  Usage3: BMDFMtrc -l|--log-last-screen [<log_file_name>]
  Usage4: BMDFMtrc -L|--log-all-screens [<log_file_name>]

Runtime environment variable dump:
  BM_DFM_TRACER_LOG__TERM_WIDE=0;
  BM_DFM_CONNECTION_FILE_path="/tmp/.BMDFMsrv";
  BM_DFM_CONNECTION_NPIP_path="/tmp/.BMDFMsrv_npipe";

.SH SEE ALSO
fastlisp.doc BMDFMdoc.pdf BMDFMfaq.pdf BMDFMbld.pdf BMDFMphd.pdf

.SH AUTHOR
Originally written by:
 Oleksandr Pochayevets (aka Sancho Mining)

